---
# tasks file for install_dependencies

- name: Run the equivalent of "apt-get update" as a separate step
  action: "{{ ansible_pkg_mgr }} update_cache=yes"
  become: true

- name: Install build-essential
  action: "{{ ansible_pkg_mgr }} pkg=build-essential"
  become: true

- name: Remove old go bin directory
  file:
    path: "{{ ansible_env.HOME }}/.go"
    state: absent

- name: Download go installer
  get_url:
    url: https://gist.githubusercontent.com/jdkanani/e18e14910652ad829fad994e4b89f0b9/raw/036bec312799cec8589360d0d939cc5ec0e7f719/go-install.sh
    dest: "{{ ansible_env.HOME }}/go-install.sh"

- name: Execute the go-install.sh
  command: "bash go-install.sh"
  args:
    chdir: "{{ ansible_env.HOME }}"

- name: Remove the go-install.sh
  file:
    path: "{{ ansible_env.HOME }}/go-install.sh"
    state: absent

- name: Creating symlink for golang
  file:
    src: "{{ ansible_env.HOME }}/.go/bin/go"
    dest: "/usr/bin/go"
    state: link
  become: true

- name: Install jq
  action: "{{ ansible_pkg_mgr }} pkg=jq"
  become: true
  
- name: Install git
  action: "{{ ansible_pkg_mgr }} pkg=git"
  become: true

- name: Install rabbitmq-server
  action: "{{ ansible_pkg_mgr }} pkg=rabbitmq-server"
  become: true
