---
- name: Network node management
  hosts: all
  tasks:
    - name: Install Erlang for RabbitMQ
      include_role:
        name: mateothegreat.erlang
        apply:
          tags: always
      tags:
        - install_erlang
  
    - name: Install RabbitMQ
      include_role:
        name: geerlingguy.rabbitmq
        apply:
          tags: always
      tags:
        - install_rabbitmq
  
    - name: Install dependencies
      include_role:
        name: roles/install-dependencies
        apply:
          tags: always
      tags:
        - install_dependencies

    - name: Build Heimdall
      include_role:
        name: roles/install-heimdall
        apply:
          tags: always
      tags:
        - build

    - name: Build Bor
      include_role:
        name: roles/install-bor
        apply:
          tags: always
      tags:
        - build

    - name: Setup and deploy network
      include_role:
        name: roles/setup-network
        apply:
          tags: always
      tags:
        - deploy
